image: maven:3.6.3

pipelines:
  default:
    - parallel:
      - step:
          name: Build, Test, Package
          caches:
            - maven
          script:
            - mvn -B clean verify
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            - pipe: atlassian/git-secrets-scan:0.5.1