# 1. build phase
FROM maven:3.9.14-eclipse-temurin-25-noble AS build
WORKDIR /app
COPY . .
RUN mvn -B -q package -DskipTests

# 2. runtime phase
FROM gcr.io/distroless/java25-debian13
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
