spring:
  application.name: ichiro-family-tree
  config.import: optional:file:.env[.properties] # enable scanning of .env file for environment variables
server.port: ${PORT:8080} # use PORT set by Heroku, otherwise 8080

page:
  url: https://voices-of-peace.live/
  refresh-interval.milliseconds: 300000
  selector: '#rec434017840 > div > div > div.t185__butwrapper.t-col.t-col_2 > a'
  attribute: href

sender:
  address: dario.mauri9@gmail.com
  password: ${SENDER_PASSWORD}
recipient.addresses: dario.mauri9@gmail.com, elen.tseller@gmail.com
