spring:
  application.name: page-checker
  config.import: optional:file:.env[.properties] # enable scanning of .env file

server.port: ${PORT:8084}

page:
  url: https://www.ikea.com/cz/en/p/landskrona-3-seat-sofa-gunnared-light-green-metal-s49270321/
  refresh-interval.ms: 300000 # 5 minutes
  selector: '#pip-buy-module-content > div.js-buy-module.pip-buy-module > div > div > div > button > span > span'
  attribute: 'Add to bag'

sender:
  address: dario.mauri9@gmail.com
  password: ${SENDER_PASSWORD}
recipient.addresses: dario.mauri9@gmail.com, elen.tseller@gmail.com
